# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incoming_date', models.DateTimeField(verbose_name='date incoming')),
                ('Incoming_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128)),
                ('material_code', models.CharField(max_length=20)),
                ('control_code', models.CharField(max_length=20)),
                ('unit', models.CharField(default='BOX', max_length=10)),
                ('memo', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgoing_date', models.DateTimeField(verbose_name='date outgoing')),
                ('outgoing_count', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='outgoing',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Pallet'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Zone'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Pallet'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Zone'),
        ),
    ]
