# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20160627_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='Incoming_count',
            new_name='incoming_count',
        ),
        migrations.RenameField(
            model_name='incoming',
            old_name='Incoming_date',
            new_name='incoming_date',
        ),
    ]
