# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20160716_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='incoming_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 20, 52, 29, 30493)),
        ),
    ]
