# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20160717_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='incoming_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='outgoing_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
